version: "2"

services:
  backend_api:
    build: backend_api
    ports:
      - 8000:8000
    container_name: backend_api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend_api:8000/"]

  frontend:
    build: frontend
    depends_on:
      - backend_api
    ports:
      - 8501:8501
    container_name: frontend
    restart: on-failure