version: "2"

services:
  backend_api:
    build: backend_api
    ports:
      - 8000:8000
    container_name: backend_api

  frontend:
    build: frontend
    depends_on:
      - backend_api
    ports:
      - 8501:8501
    container_name: frontend